### ISSUE TITLE
1.0.0 - TODO

### ISSUE THREAD

**Issue by JamesHemery** [YieldStudio/nova-google-polygon#1]
- [ ] Add the possibility to customize the shape options
- [ ] Add the possibility to customize the map options
- [x] Add ability to customize center coordinates
- [ ] Add ability to enable draggable shape
- [x] Polygon class
- [x] Point class
- [x] Custom cast
- [ ] Documentation
- [ ] Mysql Polygon Compat

**Comment by aljabr** [comment]
hi,
any update for Mysql Polygon Compat.

Thank you.

**Comment by JamesHemery** [comment]
Hi @aljabr,

Not yet, but you can open a PR if you want :)
